version: "3.8"

services:
  backend:
    build: .
    container_name: remedio-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: remedio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remediodb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build: .
    container_name: remedio-test
    command: pytest --maxfail=1 --disable-warnings --tb=short
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - db

volumes:
  postgres_data:


