services:
  backend:
    build: .
    container_name: remedio-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - remedio_net

  db:
    image: postgres:15
    container_name: remedio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remediodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - remedio_net

  test:
    container_name: remedio-test
    build: .
    command: pytest --maxfail=1 --disable-warnings --tb=short
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - db
    networks:
      - remedio_net

volumes:
  postgres_data:

networks:
  remedio_net:
    external: true
