name: Backend - Verifica Build Docker

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '**/*.py'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose
        run: |
          docker compose up --build 
